figure;
plot(SIR_dBs, mean(sum(sumrateSIR_baseline_maxrate,1),3)   , 'b-', ...
     SIR_dBs, mean(sum(sumrateSIR_baseline_maxsinr,1),3)   , 'r-', ...
     SIR_dBs, mean(sum(sumrateSIR_maxrate,1),3)            , 'b--', ...
     SIR_dBs, mean(sum(sumrateSIR_maxsinr,1),3)            , 'r--', ...
     SIR_dBs, mean(sum(sumrateSIR_baseline_tdma,1),3)      , 'c-', ...
		 SIR_dBs, mean(sum(sumrateSIR_baseline_tdma_intra,1),3), 'c-.', ...
     SIR_dBs, mean(sum(sumrateSIR_baseline_unc ,1),3)      , 'k-');
legend('MaxRate perfect', 'MaxSINR perfect', 'MaxRate', 'MaxSINR', 'TDMA WF', 'Intra-cell TDMA only', 'Unc WF','Location','SouthEast');
xlabel('SIR [dB]'); ylabel('Sum rate [bpcu]');
title(sprintf('Nsim = %d, Kt = %d, Kc = %d, Mt = %d, Mr = %d, Nd = %d, MS\\_r = %d, SNRd\\_dB = %d, SNRu\\_dB = %d',Nsim,Kt,Kc,Mt,Mr,Nd,MS_robustification,SNRd_dB,SNRu_dB));
